### ISSUE TITLE
again mistakes in detecting build status: aborted or failure

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#232]
Below stacktrace is detected as aborted and that's incorrect:

BUILD FAILURE:
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18:test (default-test) on project tests: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.18:test failed: There was an error in the forked process
[ERROR] java.lang.ExceptionInInitializerError
[ERROR] at com.qaprosoft.carina.core.foundation.report.ReportContext.removeOldReports(ReportContext.java:328)
[ERROR] at com.qaprosoft.carina.core.foundation.report.ReportContext.getBaseDir(ReportContext.java:102)
[ERROR] at com.qaprosoft.carina.core.foundation.report.ReportContext.getTestDir(ReportContext.java:269)
[ERROR] at com.qaprosoft.carina.core.foundation.log.ThreadLogAppender.append(ThreadLogAppender.java:54)
[ERROR] at org.apache.log4j.AppenderSkeleton.doAppend(AppenderSkeleton.java:251)
[ERROR] at org.apache.log4j.helpers.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:66)
[ERROR] at org.apache.log4j.Category.callAppenders(Category.java:206)
[ERROR] at org.apache.log4j.Category.forcedLog(Category.java:391)

**Comment by vdelendik** [comment]
it should be fixed on zafira level
