### ISSUE TITLE
new zafira server/client can't register queue via pipeline

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#336]
zafira: 3.3.47
zafira-client: 3.3.51

HttpMethod: POST
URL: https://stage.qaprosoft.farm/zafira-ws/api/tests/runs/queue
Content-type: application/json
Authorization: *****
Sending request to url: https://stage.qaprosoft.farm/zafira-ws/api/tests/runs/queue
Response Code: HTTP/1.1 500 Internal Server Error
[Pipeline] echo
java.lang.IllegalStateException: hudson.AbortException: Fail: the returned code 500 is not in the accepted range: [[200‥401]]
	at jenkins.plugins.http_request.HttpRequestExecution.call(HttpRequestExecution.java:198)
	at jenkins.plugins.http_request.HttpRequestExecution.call(HttpRequestExecution.java:67)
	at hudson.remoting.LocalChannel.call(LocalChannel.java:45)
	at jenkins.plugins.http_request.HttpRequestStep$Execution.run(HttpRequestStep.java:303)
	at jenkins.plugins.http_request.HttpRequestStep$Execution.run(HttpRequestStep.java:285)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
	at hudson.security.ACL.impersonate(ACL.java:290)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by tsvrko** [comment]
fixed in 4.1
