### ISSUE TITLE
potential NPE in ZafiraUpdater.setBuildResult

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#643]
java.lang.NullPointerException: Cannot invoke method hashCode() on null object
	at org.codehaus.groovy.runtime.NullObject.hashCode(NullObject.java:174)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.dump(DefaultGroovyMethods.java:291)
	at org.codehaus.groovy.runtime.dgm$157.doMethodInvoke(Unknown Source)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:42)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:35)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:20)
	at com.qaprosoft.jenkins.pipeline.integration.zafira.ZafiraUpdater.setBuildResult(file:/var/lib/jenkins/jobs/.../builds/6/libs/QPS-Pipeline/src/com/qaprosoft/jenkins/pipeline/integration/zafira/ZafiraUpdater.groovy:145)

**Comment by vdelendik** [comment]
https://github.com/qaprosoft/qps-pipeline/commit/e64e5723307dea2ec03a753db463729ffd89d011
@okamara, please make sure Dmitry could test it correctly.
Scenario: 
1) stop Zafira container
2) run any test on CI
test is finished, no ZafiraReport and no nullpoiner in logs

**Comment by okamara** [comment]
Verified. nullpoiner is present in logs.

**Comment by dhreben** [comment]
Launched and finished  Api-Demo-Test
Nullpoiner is present in logs:
com.qaprosoft.zafira.listener.ZafiraEventRegistrar - Undefined error during test run registration!
java.lang.NullPointerException: null
	at com.qaprosoft.zafira.listener.ZafiraEventRegistrar.onSuiteStart(ZafiraEventRegistrar.java:142) [zafira-client-4.1.67.jar:?]
	at com.qaprosoft.zafira.listener.ZafiraListener.onStart(ZafiraListener.java:52) [zafira-client-4.1.67.jar:?]
	at org.testng.SuiteRunner.invokeListeners(SuiteRunner.java:301) [testng-6.14.3.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:362) [testng-6.14.3.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) [testng-6.14.3.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84) [testng-6.14.3.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208) [testng-6.14.3.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137) [testng-6.14.3.jar:?]
	at org.testng.TestNG.runSuites(TestNG.java:1049) [testng-6.14.3.jar:?]
	at org.testng.TestNG.run(TestNG.java:1017) [testng-6.14.3.jar:?]
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283) [surefire-testng-3.0.0-M3.jar:3.0.0-M3]
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75) [surefire-testng-3.0.0-M3.jar:3.0.0-M3]
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120) [surefire-testng-3.0.0-M3.jar:3.0.0-M3]
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384) [surefire-booter-3.0.0-M3.jar:3.0.0-M3]
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345) [surefire-booter-3.0.0-M3.jar:3.0.0-M3]
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126) [surefire-booter-3.0.0-M3.jar:3.0.0-M3]
	at

**Comment by vdelendik** [comment]
@dhreben @okamara test one more time using zbr-disable branch

**Comment by okamara** [comment]
Fixed.
