### ISSUE TITLE
delete organization job should remove custom project based security

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#701]
DeletOrganization pipeline should delete custom "Project-based Matrix Authorization Strategy" authorization if any.
@ilya-varchenya - ask @tsvrko about details

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/qps-pipeline/pull/737/files

**Comment by ilya-varchenya** [comment]
@vdelendik, how to check this deletion?
![image](https://user-images.githubusercontent.com/44428408/81782046-e3f1c500-9501-11ea-9f09-a1b64229ca9d.png)

**Comment by vdelendik** [comment]
[Pipeline] End of Pipeline
hudson.remoting.ProxyException: groovy.lang.MissingPropertyException: No such property: it for class: com.qaprosoft.jenkins.pipeline.Organization
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.getProperty(ScriptBytecodeAdapter.java:458)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.getProperty(DefaultInvoker.java:39)
	at com.cloudbees.groovy.cps.impl.PropertyAccessBlock.rawGet(PropertyAccessBlock.java:20)
	at com.qaprosoft.jenkins.pipeline.Organization.deleteUserFolderPermissions(Organization.groovy:265)
	at com.qaprosoft.jenkins.pipeline.Organization.deleteFolder(Organization.groovy:115)

**Comment by vdelendik** [comment]
moved to 5.1 and removed from 5.0 as it wasn't tested as result doesn't work: https://github.com/qaprosoft/qps-pipeline/pull/760

need investigate howto remove users from global project based auth strategy
