### ISSUE TITLE
on latest jenkins isLabelApplied can't parse PR data 

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#749]
java.lang.NullPointerException: Cannot invoke method getRepository() on null object
	at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:48)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:35)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:20)
	at com.qaprosoft.jenkins.pipeline.Executor.isLabelApplied(Executor.groovy:327)

**Comment by vdelendik** [comment]
fixed: https://github.com/qaprosoft/qps-pipeline/pull/772
no need to verify as it works perfectly on prod CI
