### ISSUE TITLE
The run that aborted in Jenkins isn't processed in Zebrunnner.

### ISSUE THREAD

**Issue by dzmitry-pinchuk** [qaprosoft/qps-pipeline#805]
After aborting in Jenkins, run is active in Zebrunner.

Log from Jenkins:
`Please refer to /var/jenkins_home/jobs/projectName/jobs/Suite/workspace/././target/surefire-reports for the individual test results.
Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Command was /bin/sh -c cd /var/jenkins_home/jobs/projectName/jobs/Suite/workspace/./. && /usr/lib/jvm/java-1.8-openjdk/jre/bin/java -javaagent:/var/jenkins_home/.m2/repository/org/jacoco/org.jacoco.agent/0.7.9/org.jacoco.agent-0.7.9-runtime.jar=destfile=/var/jenkins_home/jobs/projectName/jobs/Suite/workspace/././target/jacoco.exec org.apache.maven.surefire.booter.ForkedBooter /var/jenkins_home/jobs/projectName/jobs/Suite/workspace/target/surefire 2020-06-11T04-00-53_903-jvmRun1 surefire1578788927371731525tmp surefire_03581727748868857335tmp
Error occurred in starting fork, check output in log
Process Exit Code: 1
Crashed tests:
testName
org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Command was /bin/sh -c cd /var/jenkins_home/jobs/projectName/jobs/Suite/workspace/./. && /usr/lib/jvm/java-1.8-openjdk/jre/bin/java -javaagent:/var/jenkins_home/.m2/repository/org/jacoco/org.jacoco.agent/0.7.9/org.jacoco.agent-0.7.9-runtime.jar=destfile=/var/jenkins_home/jobs/projectName/jobs/Suite/workspace/././target/jacoco.exec org.apache.maven.surefire.booter.ForkedBooter /var/jenkins_home/jobs/projectName/jobs/Suite/workspace/target/surefire 2020-06-11T04-00-53_903-jvmRun1 surefire1578788927371731525tmp surefire_03581727748868857335tmp
Error occurred in starting fork, check output in log
Process Exit Code: 1
Crashed tests:
testName
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:669)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:282)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:245)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1183)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1011)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:857)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)`

**Comment by ilya-varchenya** [comment]
Close ticket because it hasn't reproduced
