### ISSUE TITLE
unable to trigger testrail updater

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-pipeline#882]
hudson.remoting.ProxyException: groovy.lang.MissingMethodException: No signature of method: com.ua.jenkins.pipeline.UARunner.getCurrentFolderFullName() is applicable for argument types: (java.lang.String) values: [testrail-updater]
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:58)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:54)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:20)
	at com.qaprosoft.jenkins.pipeline.runner.maven.TestNG.runJob(TestNG.groovy:580)
	at ___cps.transform___(Native Method)

**Comment by vdelendik** [comment]
fixed: https://github.com/qaprosoft/qps-pipeline/commit/715fe1ca29f8efd994ef78f400466d54b73f1a59

**Comment by dhreben** [comment]
@vdelendik could you please add details or steps how I can test this ticket?

**Comment by okamara** [comment]
Tested on customer. Fixed.
